apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy.fullname" . }}
  labels:
    {{- include "nginx-proxy.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-proxy.selectorLabels" . | nindent 4 }}
