apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # NLB로 변경
  labels:
    {{- include "nginx-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nginx-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
